### PR TITLE
Add scoop support

### PR DESCRIPTION
**Pull request by Armaldio**
Hey 👋 

I have an [open PR](https://github.com/ScoopInstaller/Main/pull/1574) for fnm on scoop.
Keeping this as draft until merged.

Feel free to write better Readme if the current changes doesn't fit 🙂

### CODE REVIEW

**Comment by Schniz** [comment]
Exciting!

**Comment by Armaldio** [comment]
PR was merged 🎉

**Comment by Schniz** [comment]
Can we move the entire block to "manual" (like Homebrew is for OSX)? The "with script" heading is for using an installation script which also installs the `fnm env` to your shell. Then, we can think on how to make the installation script work on Windows as well (it is currently a Bash script)

Thanks again!

**Comment by Armaldio** [comment]
Like this ?

**Review by Schniz — APPROVED** [review]
Thanks! amazing!

**Pull request merged**
