### PR TITLE
Add ARM handling to installation script

### LINKED ISSUE #302: Installation script does not work on Raspberry Pi
I figured out that with #222 and #276 `fnm` should work on a Raspberry Pi but unfortunately it doesn't. On a fresh system I tried:

```sh
pi on raspberrypi in ~ 
✖ curl -fsSL https://fnm.vercel.app/install | bash
Checking dependencies for the installation script...
Checking availability of curl... OK!
Checking availability of unzip... OK!
Downloading https://github.com/Schniz/fnm/releases/latest/download/fnm-linux.zip...
######################################################################## 100.0%##O#- #                ######################################################################## 100.0%##=O#- #               ######################################################################## 100.0%
Installing for Zsh. Appending the following to /home/pi/.zshrc:

  # fnm
  export PATH=/home/pi/.fnm:$PATH
  eval "`fnm env`"

In order to apply the changes, open a new terminal or run the following command:

  source /home/pi/.zshrc
```

But then I get a

```sh
pi on raspberrypi in ~
❯ fnm --version
zsh: exec format error: fnm
```

### PR DESCRIPTION
**Pull request by Schniz**
Fixes #302

cc @screendriver

### CODE REVIEW

**Comment by Schniz** [comment]
@screendriver

can you please try

```
curl https://fnm-git-install-script-arm.schniz.vercel.app | bash
```

to see what it installs for you? 😄

**Comment by screendriver** [comment]
> @screendriver
> 
> can you please try
> 
> ```
> curl https://fnm-git-install-script-arm.schniz.vercel.app | bash
> ```
> 
> to see what it installs for you? 😄

Now I'm getting a 

```sh
pi on raspberrypi in ~ 
❯ curl https://fnm-git-install-script-arm.schniz.vercel.app | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    51    0    51    0     0    125      0 --:--:-- --:--:-- --:--:--   125
bash: line 1: syntax error near unexpected token `('
bash: line 1: `Redirecting to https://github.com/Schniz/fnm (308)'
```

**Comment by Schniz** [comment]
@screendriver
sorry I meant

```
curl https://fnm-git-install-script-arm.schniz.vercel.app/install | bash
```

But I have added a test so I think it's going to work 😄 
make sure that on armv7l you're going to need `libatomic1` to run Node (that is installed from binary)

**Comment by Schniz** [comment]
@screendriver let me know if you want to test it out, or I should just merge because I added tests 😄  (I don't know if the docker images emulate Raspberry Pi correctly...)

**Comment by screendriver** [comment]
> curl https://fnm-git-install-script-arm.schniz.vercel.app/install | bash

Works! 🎉 Thanks! 👍

**Pull request merged**
