### PR TITLE
Mention fnm omf plugin for Fish users

### LINKED ISSUE #105: Fish completions
Are there any plans for adding `fish` completions? ~~Perhaps this could be achieved with a man page, as it would probably be better than having third-party completions from, for example, an Oh My Fish plugin.~~ Maybe the installation script could add completions to [`~/.config/fish/completions`](https://fishshell.com/docs/current/index.html#completion-path), as this could allow for completions similar to [`plugin-nvm`](https://github.com/derekstavis/plugin-nvm/blob/master/completions/nvm.fish).

### PR DESCRIPTION
**Pull request by idkjs**
I dont know if this is necessary but here it is if you want it.

Fixes #105

### CODE REVIEW

**Comment by Schniz** [comment]
Sounds good to me — if that helps people, why not adding it to the README? 😄

**Comment by Schniz** [comment]
Please mark it as ready if you want to merge it 😄

**Comment by idkjs** [comment]
Ready.

**Comment by Schniz** [comment]
Thanks! 😁

**Comment by thomsj** [comment]
The [script I wrote](https://github.com/thomsj/fnm/blob/fish-completions/fish/completions/fnm.fish) (mentioned in [this comment](https://github.com/Schniz/fnm/issues/105#issuecomment-504720963)) for #105 covers quite a few things the one added to the README doesn't. It doesn't work with fish 2 though, I think just because I used `set -a`.

I'd still like to (try to) do what we discussed in #105, @Schniz, if I ever find the time. Are you still interested in the idea? I'm happy for you to leave the issue closed either way. 🙂

**Comment by idkjs** [comment]
@thomsj I would love to get closely aquainted with fish. Count me in your want some help for someone less skills then @Schniz

**Comment by thomsj** [comment]
Thanks @idkjs. If you want to try my completions, you could put the file in the [`completions` directory](https://fishshell.com/docs/current/#where-to-put-completions).

I suppose I could publish the completions as an Oh My Fish plugin, but I don't know that much about omf, or how/when it runs plugin scripts. I do use omf, but I think the only plugin I use is [bobthefish](https://github.com/oh-my-fish/theme-bobthefish).

**Comment by idkjs** [comment]
Will do.

**Pull request merged**
