### PR TITLE
Fix typo criterias -> criteria

### PR DESCRIPTION
**Pull request by waldyrious**
"criteria" is already in the plural form. The singlular is "criterion".

### CODE REVIEW

**Comment by tatchi** [comment]
> "criteria" is already in the plural form. The singlular is "criterion".

Oups sorry for that 😅

**Comment by waldyrious** [comment]
@tatchi I learned that myself not long ago :) it's a pretty common mixup.

**Comment by Schniz** [comment]
Can you please run `esy fmt` so formatting will be preserved? 😁 

(💡 I wonder if I can use GH actions to run `esy fmt` on a repo with a comment 💡 )

**Comment by Schniz** [comment]
Other than that, thanks! English is a hard language 🤷‍♂ I didn't know that "criteria" is the plural form either. In Hebrew, we say "criterion" for singular and "criterion-im" (which is like saying "criterions") 😅 

so thanks for chiming in and fixing that 👏

**Comment by waldyrious** [comment]
I wasn't able to get `esy fmt` to work :( Here's what I did and the output:

<details>

```
❯ npm install -g esy
/Users/waldyrious/.fnm/node-versions/v9.11.2/installation/bin/esy -> /Users/waldyrious/.fnm/node-versions/v9.11.2/installation/lib/node_modules/esy/_build/default/bin/esy.exe

> esy-solve-cudf@0.1.10 postinstall /Users/waldyrious/.fnm/node-versions/v9.11.2/installation/lib/node_modules/esy/node_modules/esy-solve-cudf
> node ./postinstall.js


> esy@0.6.2 postinstall /Users/waldyrious/.fnm/node-versions/v9.11.2/installation/lib/node_modules/esy
> node ./postinstall.js

+ esy@0.6.2
added 2 packages in 12.281s

~/Developer/fnm fix-criterias-typo 14s
❯ esy fmt
error: project is not installed, run `esy install`

esy: exiting due to errors above

~/Developer/fnm fix-criterias-typo
❯ esy install
info install 0.6.2 (using package.json)
info fetching: done
info installing: done

~/Developer/fnm fix-criterias-typo 59s
❯ esy fmt
info building @esy-ocaml/substs@0.0.1@d41d8cd9
info building ocaml@4.8.1000@d41d8cd9
info building @opam/conf-gmp@archive:https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz#sha1:9dc6981197a7d92f339192eea974f5eca48fcffe@7e96a8d6
info building pesy@0.4.4@d41d8cd9
info building @esy-ocaml/substs@0.0.1@d41d8cd9: done
info building @opam/conf-perl@opam:1@a6896ba6
info building @opam/conf-m4@opam:1@3b2b148a
info building @opam/base-unix@opam:base@87d0b2eb
info building @opam/base-threads@opam:base@36803084
info building pesy@0.4.4@d41d8cd9: done
info building @opam/base-threads@opam:base@36803084: done
info building @opam/base-unix@opam:base@87d0b2eb: done
info building @opam/conf-perl@opam:1@a6896ba6: done
info building @opam/conf-m4@opam:1@3b2b148a: done
info building ocaml@4.8.1000@d41d8cd9: done
info building @opam/ocamlfind@opam:1.8.1@ff07b0f9
info building @opam/dune@opam:2.3.0@3dc35de7
info building @opam/cmdliner@opam:1.0.4@93208aac
info building @opam/ocamlbuild@opam:0.14.0@6ac75d03
info building @opam/seq@opam:base@d8d7de1d
info building @opam/mirage-no-solo5@opam:1@84049e1f
info building @opam/mirage-no-xen@opam:1@0d45465b
info building @opam/mirage-no-xen@opam:1@0d45465b: done
info building @opam/jbuilder@opam:1.0+beta20.2@053ddcf2
info building @opam/mirage-no-solo5@opam:1@84049e1f: done
info building @opam/seq@opam:base@d8d7de1d: done
info building @opam/cmdliner@opam:1.0.4@93208aac: done
info building @opam/ocamlfind@opam:1.8.1@ff07b0f9: done
info building @opam/base-bytes@opam:base@19d0c2ff
info building @opam/num@opam:1.3@43fe4f7f
info building @opam/base-bytes@opam:base@19d0c2ff: done
info building @opam/ocamlbuild@opam:0.14.0@6ac75d03: done
info building @opam/topkg@opam:1.0.1@a42c631e
info building @opam/uchar@opam:0.0.2@c8218eea
info building @opam/num@opam:1.3@43fe4f7f: done
info building @opam/uchar@opam:0.0.2@c8218eea: done
info building @opam/jbuilder@opam:1.0+beta20.2@053ddcf2: done
info building @opam/topkg@opam:1.0.1@a42c631e: done
info building @opam/uutf@opam:1.0.2@4440868f
info building @opam/astring@opam:0.8.3@4e5e17d5
info building @opam/uutf@opam:1.0.2@4440868f: done
info building @opam/jsonm@opam:1.0.1@ad3e76f5
info building @opam/astring@opam:0.8.3@4e5e17d5: done
info building @opam/jsonm@opam:1.0.1@ad3e76f5: done
info building @opam/dune@opam:2.3.0@3dc35de7: done
info building @opam/stringext@opam:1.6.0@104bc94b
info building @opam/cppo@opam:1.6.6@f4f83858
info building @opam/menhirLib@opam:20200211@99279102
info building @opam/menhirSdk@opam:20200211@1b43927c
info building @opam/ppx_derivers@opam:1.2.1@ecf0aa45
info building @opam/result@opam:1.4@dc720aef
info building @opam/dune-private-libs@opam:2.3.0@0e3e8465
info building @opam/ppx_derivers@opam:1.2.1@ecf0aa45: done
info building @opam/sexplib0@opam:v0.13.0@3f54c2be
info building @opam/result@opam:1.4@dc720aef: done
info building @opam/ocaml-compiler-libs@opam:v0.12.1@5c34eb0d
info building @opam/stringext@opam:1.6.0@104bc94b: done
info building @opam/re@opam:1.9.0@d4d5e13d
info building @opam/menhirSdk@opam:20200211@1b43927c: done
info building @opam/stdlib-shims@opam:0.1.0@d957c903
info building @opam/sexplib0@opam:v0.13.0@3f54c2be: done
info building @opam/mmap@opam:1.1.0@b85334ff
info building @opam/cppo@opam:1.6.6@f4f83858: done
info building @opam/macaddr@opam:4.0.0@db328173
info building @opam/stdlib-shims@opam:0.1.0@d957c903: done
info building @opam/bigarray-compat@opam:1.0.0@1faefa97
info building @opam/menhirLib@opam:20200211@99279102: done
info building @opam/cpuid@opam:0.1.2@469a8b76
info building @opam/mmap@opam:1.1.0@b85334ff: done
info building @opam/ppx_tools@opam:6.0+4.08.0@5f5453f4
info building @opam/bigarray-compat@opam:1.0.0@1faefa97: done
info building @opam/gmap@opam:0.3.0@599a6bf7
info building @opam/macaddr@opam:4.0.0@db328173: done
info building @opam/magic-mime@opam:1.1.2@980f82fb
info building @opam/cpuid@opam:0.1.2@469a8b76: done
info building @opam/markup@opam:0.8.2@87975241
info building @opam/gmap@opam:0.3.0@599a6bf7: done
info building @opam/easy-format@opam:1.3.2@0484b3c4
info building @opam/re@opam:1.9.0@d4d5e13d: done
info building @esy-ocaml/fauxpam@0.2.0@d41d8cd9
info building @opam/ocaml-compiler-libs@opam:v0.12.1@5c34eb0d: done
info building @opam/ocaml-migrate-parsetree@opam:1.6.0@da2643e7
info building @opam/easy-format@opam:1.3.2@0484b3c4: done
info building @opam/rresult@opam:0.6.0@4b185e72
info building @esy-ocaml/fauxpam@0.2.0@d41d8cd9: done
info building @opam/ptime@opam:0.8.5@0051d642
info building @opam/magic-mime@opam:1.1.2@980f82fb: done
info building @opam/ocplib-endian@opam:1.0@aa720242
info building @opam/rresult@opam:0.6.0@4b185e72: done
info building @opam/merlin-extend@opam:0.5@a5dd7d4b
info building @opam/merlin-extend@opam:0.5@a5dd7d4b: done
info building @opam/fmt@opam:0.8.8@01c3a23c
info building @opam/ptime@opam:0.8.5@0051d642: done
info building @opam/menhir@opam:20200211@90483d81
info building @opam/fmt@opam:0.8.8@01c3a23c: done
info building @opam/cstruct@opam:5.1.1@e0b5aafd
info building @opam/markup@opam:0.8.2@87975241: done
info building @opam/tyxml@opam:4.3.0@c1da25f1
info building @opam/cstruct@opam:5.1.1@e0b5aafd: done
info building @opam/uri@opam:3.1.0@d38ac0ae
info building @opam/ppx_tools@opam:6.0+4.08.0@5f5453f4: done
info building @opam/biniou@opam:1.2.1@d7570399
info building @opam/biniou@opam:1.2.1@d7570399: done
info building @opam/ocb-stubblr@opam:0.1.1-1@fa95dcc0
info building @opam/ocb-stubblr@opam:0.1.1-1@fa95dcc0: done
info building @opam/domain-name@opam:0.3.0@af116067
info building @opam/domain-name@opam:0.3.0@af116067: done
info building @opam/lambdasoup@opam:0.7.0@a04ae670
info building @opam/dune-private-libs@opam:2.3.0@0e3e8465: done
info building @opam/yojson@opam:1.7.0@7056d985
info building @opam/lambdasoup@opam:0.7.0@a04ae670: done
info building @opam/ipaddr@opam:4.0.0@af37ddc7
info building @opam/ipaddr@opam:4.0.0@af37ddc7: done
info building @opam/dune-configurator@opam:2.3.0@cf20be6b
info building @opam/ocplib-endian@opam:1.0@aa720242: done
info building @opam/yojson@opam:1.7.0@7056d985: done
info building @opam/atdgen-runtime@opam:2.0.0@60f6faab
info building @opam/merlin@opam:3.3.3@d653b06a
info building @opam/uri@opam:3.1.0@d38ac0ae: done
info building @opam/tyxml@opam:4.3.0@c1da25f1: done
info building @opam/junit@opam:2.0.2@0b7bd730
info building @opam/atdgen-runtime@opam:2.0.0@60f6faab: done
info building @opam/junit@opam:2.0.2@0b7bd730: done
info building @opam/dune-configurator@opam:2.3.0@cf20be6b: done
info building @opam/lwt@opam:5.1.1@6f0a0b20
info building @opam/base@opam:v0.13.1@7d937ed0
info building @opam/base64@opam:3.3.0@d900b2d8
info building @opam/base64@opam:3.3.0@d900b2d8: done
info building @opam/menhir@opam:20200211@90483d81: done
info building @opam/atd@opam:2.0.0@e0ddd12f
info building @opam/ocaml-migrate-parsetree@opam:1.6.0@da2643e7: done
info building @esy-ocaml/reason@3.5.2@d41d8cd9
info building @opam/ppxfind@opam:1.4@c51fd7bf
info building @opam/ppx_tools_versioned@opam:5.2.3@4994ec80
info building @opam/atd@opam:2.0.0@e0ddd12f: done
info building @opam/atdgen@opam:2.0.0@46af0360
info building @opam/ppxfind@opam:1.4@c51fd7bf: done
info building @opam/ppx_deriving@opam:4.4@21d6c7a5
info building @opam/lwt@opam:5.1.1@6f0a0b20: done
info building @opam/cstruct-lwt@opam:5.1.1@8923fbc9
info building @opam/cstruct-lwt@opam:5.1.1@8923fbc9: done
info building @opam/logs@opam:0.7.0@1d03143e
info building @opam/atdgen@opam:2.0.0@46af0360: done
info building @opam/logs@opam:0.7.0@1d03143e: done
info building @opam/ppx_deriving@opam:4.4@21d6c7a5: done
info building @opam/ppx_deriving_yojson@opam:3.5.1@06a1c37f
info building @opam/ppx_deriving_yojson@opam:3.5.1@06a1c37f: done
info building @opam/base@opam:v0.13.1@7d937ed0: done
info building @opam/fieldslib@opam:v0.13.0@e5d61627
info building @opam/stdio@opam:v0.13.0@eb59d879
info building @opam/parsexp@opam:v0.13.0@5b4df040
info building @opam/fieldslib@opam:v0.13.0@e5d61627: done
info building @opam/stdio@opam:v0.13.0@eb59d879: done
info building @opam/ppxlib@opam:0.12.0@fcf5cabc
info building @opam/parsexp@opam:v0.13.0@5b4df040: done
info building @opam/sexplib@opam:v0.13.0@79086695
info building @opam/ppx_tools_versioned@opam:5.2.3@4994ec80: done
info building @opam/lwt_ppx@opam:2.0.0@9a61dd37
info building @opam/sexplib@opam:v0.13.0@79086695: done
info building @opam/ppx_cstruct@opam:5.1.1@88b3aa4e
info building @opam/cstruct-sexp@opam:5.1.1@58ce0491
info building @opam/cstruct-sexp@opam:5.1.1@58ce0491: done
info building @opam/lwt_ppx@opam:2.0.0@9a61dd37: done
info building @opam/ppx_cstruct@opam:5.1.1@88b3aa4e: done
info building @opam/merlin@opam:3.3.3@d653b06a: done
info building @esy-ocaml/reason@3.5.2@d41d8cd9: done
info building @reason-native/pastel@0.2.3@d41d8cd9
info building @reason-native/console@0.1.0@d41d8cd9
info building @reason-native/console@0.1.0@d41d8cd9: done
info building @reason-native/pastel@0.2.3@d41d8cd9: done
info building refmterr@3.3.0@d41d8cd9
info building @reason-native/file-context-printer@0.0.3@d41d8cd9
info building @reason-native/file-context-printer@0.0.3@d41d8cd9: done
info building refmterr@3.3.0@d41d8cd9: done
info building @reason-native/rely@1.3.1@d41d8cd9
info building @opam/conf-gmp@archive:https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz#sha1:9dc6981197a7d92f339192eea974f5eca48fcffe@7e96a8d6: done
info building @opam/zarith@opam:1.9.1@ce833113
info building @reason-native/rely@1.3.1@d41d8cd9: done
info building @opam/zarith@opam:1.9.1@ce833113: done
info building @opam/asn1-combinators@opam:0.2.2@61f661eb
info building @opam/asn1-combinators@opam:0.2.2@61f661eb: done
info building @opam/ppxlib@opam:0.12.0@fcf5cabc: done
info building @opam/ppx_fields_conv@opam:v0.13.0@3c767913
info building @opam/ppx_let@opam:v0.13.0@5703d2be
info building @opam/ppx_sexp_conv@opam:v0.13.0@53058ed2
info building @opam/ppx_let@opam:v0.13.0@5703d2be: done
info building @opam/ppx_fields_conv@opam:v0.13.0@3c767913: done
info building @opam/ppx_sexp_conv@opam:v0.13.0@53058ed2: done
info building @opam/nocrypto@opam:0.5.4-2@723e1f42
info building @opam/ipaddr-sexp@opam:4.0.0@eee6f9bd
info building @opam/uri-sexp@opam:3.1.0@f97bddff
info building @opam/uri-sexp@opam:3.1.0@f97bddff: done
info building @opam/cohttp@opam:2.5.1@6494d505
info building @opam/ipaddr-sexp@opam:4.0.0@eee6f9bd: done
info building @opam/conduit@opam:2.0.2@2891d9d4
info building @opam/conduit@opam:2.0.2@2891d9d4: done
info building @opam/conduit-lwt@opam:2.0.2@c4809b9f
info building @opam/cohttp@opam:2.5.1@6494d505: done
info building @opam/cohttp-lwt@opam:2.5.1@addba697
info building @opam/conduit-lwt@opam:2.0.2@c4809b9f: done
info building @opam/cohttp-lwt@opam:2.5.1@addba697: done
info building @opam/nocrypto@opam:0.5.4-2@723e1f42: done
info building @opam/x509@opam:0.8.1@9fe96f81
info building @opam/x509@opam:0.8.1@9fe96f81: done
info building @opam/tls@opam:0.10.5@1fd9a963
info building @opam/tls@opam:0.10.5@1fd9a963: done
info building @opam/conduit-lwt-unix@opam:2.0.2@4f617c75
info building @opam/conduit-lwt-unix@opam:2.0.2@4f617c75: done
info building @opam/cohttp-lwt-unix@opam:2.5.1@6d59fe96
info building @opam/cohttp-lwt-unix@opam:2.5.1@6d59fe96: done
error: project is not installed, run `esy install`

esy: exiting due to errors above

~/Developer/fnm fix-criterias-typo 6m 9s
❯ esy install
info install 0.6.2 (using package.json)

~/Developer/fnm fix-criterias-typo
❯ esy fmt
error: project is not installed, run `esy install`

esy: exiting due to errors above
```
</details>

> I wonder if I can use GH actions to run `esy fmt` on a repo with a comment

Please do :) I hadn't installed `esy` because I don't know ReasonML so I didn't expect to contribute much code. Besides having to do these manual steps which could be automated in the PR, they also took a bit of time to run in a reasonably modern machine (see the timestamps in the prompts above), so that'll add a bit of initial friction to new contributors, who are precisely the ones most in need of a streamlined experience.

**Comment by tatchi** [comment]
> I wasn't able to get `esy fmt` to work :( Here's what I did and the output:
> 
> > I wonder if I can use GH actions to run `esy fmt` on a repo with a comment
> 
> Please do :) I hadn't installed `esy` because I don't know ReasonML so I didn't expect to contribute much code. Besides having to do these manual steps which could be automated in the PR, they also took a bit of time to run in a reasonably modern machine (see the timestamps in the prompts above), so that'll add a bit of initial friction to new contributors, who are precisely the ones most in need of a streamlined experience.

Yes I already experienced that issue: https://github.com/esy/esy/issues/1051#issuecomment-588425135

Try to first run `esy @fmt`

**Comment by waldyrious** [comment]
Thanks, @tatchi, that helped. This should definitely be in the README.

That said, the process was still far from smooth:

<details>

```
~/Developer/fnm fix-criterias-typo
❯ esy @fmt
info esy 0.6.2 (using fmt.json)
info fetching: done
info installing: done
info building ocaml@4.6.1000@d41d8cd9
info building ocaml@4.6.1000@d41d8cd9: done
info building @opam/ocamlbuild@opam:0.14.0@6ac75d03
info building @opam/dune@opam:1.11.3@9894df55
info building @opam/ocamlfind@opam:1.8.1@ff07b0f9
info building @opam/ocamlfind@opam:1.8.1@ff07b0f9: done
info building @opam/ocamlbuild@opam:0.14.0@6ac75d03: done
info building @opam/menhir@opam:20190924@004407ff
info building @opam/dune@opam:1.11.3@9894df55: done
info building @opam/cppo@opam:1.6.6@f4f83858
info building @opam/ppx_derivers@opam:1.2.1@ecf0aa45
info building @opam/result@opam:1.4@dc720aef
info building @opam/ppx_derivers@opam:1.2.1@ecf0aa45: done
info building @opam/result@opam:1.4@dc720aef: done
info building @opam/ocaml-migrate-parsetree@opam:1.4.0@0c4ec62d
info building @opam/cppo@opam:1.6.6@f4f83858: done
info building @opam/merlin-extend@opam:0.5@a5dd7d4b
info building @opam/merlin-extend@opam:0.5@a5dd7d4b: done
info building @opam/menhir@opam:20190924@004407ff: done
info building @opam/ocaml-migrate-parsetree@opam:1.4.0@0c4ec62d: done
info building @esy-ocaml/reason@3.5.2@d41d8cd9
info building @esy-ocaml/reason@3.5.2@d41d8cd9: done

~/Developer/fnm fix-criterias-typo 3m 23s
❯ esy fmt
File "./test/TestListRemote.re", line 61, characters 42-44:
Warning 14: illegal backslash escape in string.
File "./test/TestListRemote.re", line 61, characters 50-52:
Warning 14: illegal backslash escape in string.
File "./test/TestListRemote.re", line 61, characters 58-60:
Warning 14: illegal backslash escape in string.
File "./test/TestListRemote.re", line 67, characters 51-53:
Warning 14: illegal backslash escape in string.

~/Developer/fnm fix-criterias-typo*
❯ git add -p
diff --git a/executable/Uninstall.re b/executable/Uninstall.re
index 3c2e0dc..04f81ab 100644
--- a/executable/Uninstall.re
+++ b/executable/Uninstall.re
@@ -46,9 +46,7 @@ let run = (~version) => {
     Lwt.return_ok();
   | _ =>
     Logger.info(
-      <Pastel>
-        "There are multiple versions matching your criteria:"
-      </Pastel>,
+      <Pastel> "There are multiple versions matching your criteria:" </Pastel>,
     );
     matchingLocalVersions
     |> List.iter(matchingVersion =>
(1/1) Stage this hunk [y,n,q,a,d,e,?]? y

~/Developer/fnm fix-criterias-typo*
❯ git commit -m "Run esy fmt"
npx: installed 129 in 6.9s
lint-staged requires at least version 10.13.0 of Node, please upgrade

~/Developer/fnm fix-criterias-typo* 8s
❯ fnm use 10
Linking /var/folders/6p/m7980bc100g5q58dc14q7l6h0000gn/T/fnm-shell-457616 to /Users/waldyrious/.fnm/node-versions/v10.18.1/installation
Using v10.18.1

~/Developer/fnm fix-criterias-typo*
❯ git commit -m "Run esy fmt"
npx: installed 129 in 5.497s
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.

  ✔ Preparing...
  ❯ Running tasks...
    ❯ Running tasks for *.re
      ✖ esy @fmt refmt --in-place
        git add
    ↓ Running tasks for *.{js,md,json} [skipped]
      → No staged files match *.{js,md,json}
    ↓ Running tasks for package.json [skipped]
      → No staged files match package.json
  ↓ Applying modifications... [skipped]
    → Skipped because of errors from tasks.
  ✔ Reverting to original state...
  ✔ Cleaning up...



✖ esy found some errors. Please fix them and try committing again.

~/Developer/fnm fix-criterias-typo*
❯ esy @fmt refmt --in-place
zsh: command not found: esy

~/Developer/fnm fix-criterias-typo*
❯ npm install -g esy
/Users/waldyrious/.fnm/node-versions/v10.18.1/installation/bin/esy -> /Users/waldyrious/.fnm/node-versions/v10.18.1/installation/lib/node_modules/esy/_build/default/bin/esy.exe

> esy-solve-cudf@0.1.10 postinstall /Users/waldyrious/.fnm/node-versions/v10.18.1/installation/lib/node_modules/esy/node_modules/esy-solve-cudf
> node ./postinstall.js


> esy@0.6.2 postinstall /Users/waldyrious/.fnm/node-versions/v10.18.1/installation/lib/node_modules/esy
> node ./postinstall.js

+ esy@0.6.2
added 2 packages in 2.677s

~/Developer/fnm fix-criterias-typo*
❯ esy @fmt refmt --in-place
refmt: Cannot write in place to stdin.
Usage: refmt [OPTION]... [FILENAMES]...
Try `refmt --help' for more information.

~/Developer/fnm fix-criterias-typo* 9s
❯ esy @fmt refmt --in-place executable/Uninstall.re

~/Developer/fnm fix-criterias-typo*
❯ git commit -m "Run esy fmt"
npx: installed 129 in 5.652s
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.

  ✔ Preparing...
  ✔ Running tasks...
  ✔ Applying modifications...
  ✔ Cleaning up...
[fix-criterias-typo 6ce89c6] Run esy fmt
 1 file changed, 1 insertion(+), 3 deletions(-)

~/Developer/fnm fix-criterias-typo ⇡
❯ git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 371 bytes | 371.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:waldyrious/fnm.git
   671e828..6ce89c6  fix-criterias-typo -> fix-criterias-typo
```
</details>

@Schniz I'm not sure if the issues I had are things that could be addressed from this project's tooling or documentation, but I thought I'd document them in case they helped with exposing the issues that newcomers may face so that the process can be improved. Especially for such a simple contribution, the flow ought to be much smoother IMO :)

**Pull request merged**
