### PR TITLE
Rename duplicate entry of `fnm list` to `fnm list-remote` in documentation

### PR DESCRIPTION
**Pull request by binhonglee**

### CODE REVIEW

**Comment by Schniz** [comment]
Hey! thanks for the contribution. This is very eye-opening! The thing is, that `commands.md` is auto-generated by https://github.com/Schniz/fnm/blob/master/.ci/print-command-docs.js so it will be overridden in the next release. Do you want to look at the script to figure out what's wrong with it?

You can clone the repo and run `yarn generate-command-docs` 😃 

If not, that's totally fine and I will do it myself, and anyway thanks for opening a PR and ensuring this project goes to a better place 🙏

**Comment by binhonglee** [comment]
Thanks for the guide. I'll take a look at the script later this week and submit a fix to the script instead.

**Comment by binhonglee** [comment]
Thanks for the code pointer. I'll take a look at the script later this week and submit a fix to the script instead.

**Comment by binhonglee** [comment]
Closing in favor of #461.

**Pull request closed without merging**
