### PR TITLE
Add pre-built binaries for ARM32 and ARM64

### LINKED ISSUE #222: Add a prebuilt ARM binary
Steps followed:

- Install fnm through the script: https://github.com/Schniz/fnm#using-a-script
- Restart the terminal

Issue:

- `~/.zshrc:110: exec format error: fnm` prompts after opening a new terminal
- Running `fnm` prompts `sh: exec format error: fnm`

Environment:

Raspberry Pi under raspbian

### PR DESCRIPTION
**Pull request by Schniz**
Fixes #222

### CODE REVIEW

**Comment by Schniz** [comment]
cc @jaythomas does this build work for you? [fnm-arm64.zip](https://github.com/Schniz/fnm/files/5401344/fnm-arm64.zip)

It seems to work on a docker container running `arm64v8/ubuntu` 😸

**Comment by jaythomas** [comment]
Indeed. I have tested this on my Rockchip RK3399 and everything works as expected. :tada: 

As an aside I also compiled on my Raspberry Pi 4 and confirmed the armv7l 32-bit build works. :tada:

**Comment by Schniz** [comment]
@jaythomas I'll try to build a 32bit release as well

**Comment by Schniz** [comment]
@jaythomas would you mind testing these:
* [fnm-arm64](https://github.com/Schniz/fnm/suites/1375645369/artifacts/22576131)
* [fnm-arm32](https://github.com/Schniz/fnm/suites/1375645369/artifacts/22576130)
😁 

Looks like they work and I wonder if I set up the matrix correctly. 😸

**Comment by jaythomas** [comment]
Both builds work for me, except I am experiencing an issue with `fnm use` on zsh strangely. I would have responded sooner but I haven't had a chance to troubleshoot it yet.

```sh
$ ls
fnm  fnm-arm64.zip

$ export PATH=/home/lite/.fnm:$PATH

$ eval "`./fnm env`"

$ ./fnm use v14.11.0
Using Node v14.11.0

$ node -v
zsh: command not found: node
```

This is a clean zshell with no .zshrc set up. Bash is working though. I will have to troubleshoot more this weekend.

**Comment by Schniz** [comment]
Hmm. Can you try `fnm exec --using=14 -- node -v`?

**Comment by Schniz** [comment]
Also, try seeing what it is installing:

```
RUST_LOG=fnm=debug fnm install 14.11.0
```

Maybe it's trying to download a non-ARM version?

**Comment by jaythomas** [comment]
Maybe the problem is related to the fact I manually installed this node version? I can't run `fnm install` as I don't have the "copy patch" on this system to get around moving the tmp directory. But extracting the node install manually into the directory I am seeing these issues:

```
$ fnm install v14.11.0
Installing Node v14.11.0
warning: Version already installed at "/home/lite/.fnm/node-versions/v14.11.0"

$ ~/.fnm/node-versions/v14.11.0/bin/node -v
v14.11.0

$ fnm use 14.11.0
Using Node v14.11.0

$ node -v
bash: node: command not found

$ fnm ls
* v14.11.0
* system

$ RUST_LOG=debug fnm exec --using=14 -- node -v 
[2020-10-23T16:09:53Z INFO  fnm::choose_version_for_user_input] Using Node v14.11.0
thread 'main' panicked at 'Can't spawn program: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/commands/exec.rs:55:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

User error on my part? If we get `fnm install` fixed for Linux I will blow away the entire `.fnm` directory and start from scratch.

Also note the issue is unrelated to zsh. On my 32-bit ARM bash and zsh are fine. It is just this 64-bit ARM system I am seeing the issue with either shell.

**Comment by Schniz** [comment]
Ah, yeah. For some unknown reason I decided to make the directory structure like so:
```
~/.fnm/node-versions/VERSION/installation/bin/node
```
So the manual installation was wrong 😄

**Comment by Schniz** [comment]
@jaythomas the next builds will include #275 so you won't need to try installing manually 😁

**Comment by Schniz** [comment]
let me know how it works 😄

**Comment by jaythomas** [comment]
Yup that was my problem. :roll_eyes: Ok with these changes the arm64 build artifact is working perfectly for me too!

**Review by jaythomas — APPROVED** [review]

**Pull request merged**
