### PR TITLE
Add a LICENSE file

### PR DESCRIPTION
**Pull request by Schniz**
I just used the same license Esy uses. It is very permissive so I'm fine with that.
I'll merge it tomorrow, if someone thinks that BSD2 doesn't fit well here, please let me know!

### CODE REVIEW

**Comment by Schniz** [comment]
A thought that I had: I use static compilation on Linux, therefore I'm pretty sure I need to use LGPL as the license. Would that be a problem? Since you don't bundle it as part of your app, users could build their own apps with Node, and there won't be any problems with the law 👮

**Comment by bnb** [comment]
Would be awesome to also add `"license": "BSD-2-Clause"` to `package.json` 🙌

**Comment by Schniz** [comment]
I ran a script (added to this PR) that shows all the licenses by grepping over `esy.lock`. This is the result:

```
Apache-2.0:
  - opam/ppx_sexp_message.v0.11.0
  - opam/ppx_let.v0.11.0
  - opam/ppx_here.v0.11.0
  - opam/core.v0.11.3
  - opam/fieldslib.v0.11.0
  - opam/typerep.v0.11.0
  - opam/ppx_enumerate.v0.11.1
  - opam/ppx_pipebang.v0.11.0
  - opam/ppx_inline_test.v0.11.0
  - opam/splittable_random.v0.11.0
  - opam/ppx_optcomp.v0.11.0
  - opam/variantslib.v0.11.0
  - opam/spawn.v0.12.0
  - opam/ppx_typerep_conv.v0.11.1
  - opam/ppx_compare.v0.11.1
  - opam/ppx_hash.v0.11.1
  - opam/ppx_assert.v0.11.0
  - opam/jane-street-headers.v0.11.0
  - opam/stdio.v0.11.0
  - opam/ppx_jane.v0.11.0
  - opam/sexplib0.v0.11.0
  - opam/ppx_bin_prot.v0.11.1
  - opam/ppx_sexp_value.v0.11.0
  - opam/sexplib.v0.11.0
  - opam/core_kernel.v0.11.1
  - opam/configurator.v0.11.0
  - opam/ocaml-compiler-libs.v0.11.0
  - opam/ppx_js_style.v0.11.0
  - opam/ppx_sexp_conv.v0.11.2
  - opam/ppx_fail.v0.11.0
  - opam/ppx_fields_conv.v0.11.0
  - opam/ppx_base.v0.11.0
  - opam/ppx_custom_printf.v0.11.0
  - opam/base.v0.11.1
  - opam/parsexp.v0.11.0
  - opam/bin_prot.v0.11.0
  - opam/ppx_optional.v0.11.0
  - opam/ppx_bench.v0.11.0
  - opam/ppx_variants_conv.v0.11.1
MIT:
  - opam/merlin-extend.0.3
  - opam/ppx_tools_versioned.5.2.1
  - opam/jbuilder.transition
  - opam/ppx_expect.v0.11.1
  - opam/ppxlib.0.5.0
  - opam/dune.1.6.3
GPL-2+:
  - opam/conf-which.1
LGPL with OpenSSL linking exception:
  - opam/lwt_ppx.1.2.1
  - opam/lwt.4.1.0
LGPL-2 with OCaml linking exception:
  - opam/ocamlbuild.0.12.0
ISC:
  - opam/topkg.1.0.0
  - opam/cmdliner.1.0.3
  - opam/uutf.1.0.1
  - opam/octavius.1.2.0
BSD3:
  - opam/semver.0.1.0
  - opam/result.1.3
  - opam/ppx_derivers.1.0
LGPL 2.1 with OCaml linking exception:
  - opam/num.1.1
LGPL-2.1:
  - opam/ocaml-migrate-parsetree.1.2.0
BSD:
  - opam/markup.0.8.0
  - opam/lambdasoup.0.6.3
BSD-3-Clause:
  - opam/biniou.1.2.0
  - opam/cppo.1.6.5
GPL-3:
  - opam/conf-m4.1
typeof OCaml system:
  - opam/uchar.0.0.2
LGPL-2.0 with OCaml linking exception:
  - opam/re.1.7.3
```

Seems like I have to use `GPL-3`?

**Comment by evxn** [comment]
Hi, @Schniz you can actually add a second non-copyleft license as @bnb suggested. Because you are not making a derivative of any of the listed GPL programs. They're just dev dependencies. This would be nice cause may open the road to use your code as a base for other version managers with less-restrictive licenses.

**Comment by Schniz** [comment]
Hi. I don’t follow any legal stuff. If you’re a lawyer and think this is still true, and people really want to copy code, we need to verify the dependencies again and let’s do this. We should verify it continuously. I believe that since we’re making a static binary instead of dynamically linking it needs to be LGPL. But I’m not sure — I’m just a developer 😅

(Also maybe I’m taking this too seriously, but you can’t be too careful)

**Pull request merged**
