### PR TITLE
Fix "illegal instruction" errors on some CPUs

### LINKED ISSUE #173: illegal hardware instruction
I am getting the error 
`[1]    86284 illegal hardware instruction  fnm --version`

It happens on any usage of fnm. It used to work when installed via script on a previous version.

I'm on Mac OS 10.13.6 (High Sierra)

Installed fnm via your homebrew tap. Also tried reinstalling.

### PR DESCRIPTION
**Pull request by Schniz**
Trying to fix #173 by using @ulrikstrid's suggestion with `--enable-fat` in gmp 😄

### CODE REVIEW

**Comment by Schniz** [comment]
@ivanoats Can you try the following MacOS build?

[fnm-macos - gmp-fat.zip](https://github.com/Schniz/fnm/files/3972177/fnm-macos.-.gmp-fat.zip)

@Alexlen123 Can you try the following Linux build?

[fnm - gmp-fat.zip](https://github.com/Schniz/fnm/files/3972187/fnm.-.gmp-fat.zip)

**Comment by Axelen123** [comment]
> Can you try the following Linux build?
I tried it and ls-remote works!
It's just that the file has a .zip extension even though it is the executable and not a zip archive

**Comment by evan-hughes** [comment]
The fnm version in gmp-fat.zip worked on one of our problematic machines.

**Comment by ivanoats** [comment]
I just tried it on my Mac, and unfortunately, it still has the illegal hardware instruction error.

**Comment by Schniz** [comment]
> Note this is an old iMac (2010) and it works on my new MacBook Pro 15

can you try this build?
[fnm-macos - gmp no assembly.zip](https://github.com/Schniz/fnm/files/3977354/fnm-macos.-.gmp.no.assembly.zip)

this one is with `--disable-assembly`

Linux users:

[fnm-linux - gmp no assembly.zip](https://github.com/Schniz/fnm/files/3977357/fnm-linux.-.gmp.no.assembly.zip)

**Comment by gilly3** [comment]
Both linux builds work for me on Ubuntu 18.04 running on [WSL](https://docs.microsoft.com/en-us/windows/wsl/about).

**Comment by Schniz** [comment]
Cool! @ivanoats waiting for your input :)

**Comment by ivanoats** [comment]
Just tried it, thanks for your patience. Unfortunately, same error.

**Comment by Schniz** [comment]
> Unfortunately, same error.

@ivanoats thanks for trying again. I'm going to use the `--enable-fat` for now as it solves most issues, we need to dig in deeper to figure out what illegal instruction you're facing on your Mac, maybe it isn't related to gmp

**Pull request merged**
