### PR TITLE
This $PATH should be wrapped in quotes so it will work with spaces

### PR DESCRIPTION
**Pull request by floh1695**
This $PATH use needs to be wrapped in quotes so it will expand properly if there are spaces within the $PATH. This seems to only effect sh, not bash.

To reproduce:
1. Run `PATH="space path:$PATH"`
2. Run `eval $(fnm env)`
3. At this point I would expect you to get the error: `sh: 1: export: path:rest/off/you/path/before/next/space: bad variable name`

### CODE REVIEW

**Comment by floh1695** [comment]
The the fails for clippy and bench/linux don't seem related to what I changed. Please let me know if I'm mistaken about that.

**Comment by Schniz** [comment]
Yeah that’s fine. I will also accept a `cargo clippy —fix` PR or will try doing it today. Mind pushing a changeset so it’ll appear on the changelog? (Check out the comment by the bot for help)

**Comment by Schniz** [comment]
And thanks for contributing! I don’t take this lightly

**Comment by floh1695** [comment]
I have pushed up a patch changeset. Is that correct or should I have made it a minor change?

And no worries, thanks for providing such a great tool!

**Comment by Schniz** [comment]
Patch is good! Thank you

**Pull request merged**
