### PR TITLE
fix: panic on completions

### LINKED ISSUE #1006: 1.35.0 panics on `completions`
Steps to reproduce:
1. Download `fnm-linux.zip` from the release: https://github.com/Schniz/fnm/releases/tag/v1.35.0
2. Execute `/fnm completions`

```
$ ./fnm completions --shell zsh
thread 'main' panicked at 'built', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_complete-4.3.1/src/generator/utils.rs:124:26
```

### PR DESCRIPTION
**Pull request by quixoten**
This fixes #1006. As far as i can tell, this was broken by the clap upgrade (#991).

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
patch works for my homebrew PR.

**Comment by Schniz** [comment]
thank you! :pray:

**Comment by quixoten** [comment]
the failing tests do not seem related to this change. i'm not sure what additional steps i can take to get this merged. i looked for a way to retry the failed tests, but didn't see one.

**Comment by amirbilu** [comment]
Is this going to be merged anytime soon?

**Comment by jsomedon** [comment]
It looks like the this PR is complete and good to be merged yes?

**Comment by es20490446e** [comment]
Thanks for the fix 👍

**Pull request merged**
