### PR TITLE
Bump ocaml to 4.08

### PR DESCRIPTION
**Pull request by tatchi**
I updated OCaml to 4.08. I had also to update two others dependencies (`base` and `ppx_let`).

First time I do that so let's see if the CI pass 😆

### CODE REVIEW

**Comment by tatchi** [comment]
It failed on Linux:

```
docker: Error response from daemon: pull access denied for schlez/fnm-static-binary, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

@Schniz Do you have any idea ?

**Comment by Schniz** [comment]
> @Schniz Do you have any idea ?

The docker image creation has failed. The `.ci/create-static-binary.sh` script that I wrote does not have `set -e` on the top, making failed commands just continue instead of failing the whole script

**Comment by tatchi** [comment]
Youhhhouu 🎉🤗

**Comment by Schniz** [comment]
Thanks @tatchi! 🤑 🌮

**Pull request merged**
