### PR TITLE
fix: Use correct PATH for npm install test

### PR DESCRIPTION
**Pull request by ixti**
Resolves: https://github.com/Schniz/fnm/issues/755

### CODE REVIEW

**Comment by Schniz** [comment]
@ixti thanks for this! can you run `cargo fmt` to make sure it's formatted correctly? I can also do that if you prefer

**Comment by ixti** [comment]
@Schniz fixed. Forgot to run it beforehand. :D

**Comment by ixti** [comment]
@Schniz Hi, is there anything I can do to make this PR being merged? Would like to have smaller patch-set for my Gentoo ebuilds ;D

**Comment by Schniz** [comment]
Sorry about the delay!

**Comment by ixti** [comment]
@Schniz Thank you!

**Pull request merged**
